services:
  homepage:
    restart: always
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    expose:
      - 3000
    volumes:
      - ./../configs/services/homepage:/app/config
      - ./../configs/services/homepage/background:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.cosmdandy.ru
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.cosmdandy.ru`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=myresolver"
      - "traefik.http.routers.homepage.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.middlewares=auth"
networks:
  traefik_network:
    external: true
