---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Services
description: GO HARD OR GO HOME
theme: dark
color: slate
background:
  color: "#000000"
headerStyle: clean
hideVersion: true
bookmarksStyle: icons
statusStyle: "dot"
# useEqualHeights: true

layout:
  Lab Services:
    tab: Services
    style: row
    columns: 3
    useEqualHeights: true
  Arr Stack:
    tab: Services
    style: row
    columns: 2
  Arr Stack Search:
    tab: Services
    style: row
    columns: 4
  Torrent:
    tab: Services
    style: row
    columns: 2
  Hypervizor:
    tab: Infrastucture
    style: row
    columns: 4
    disableCollapse: true
  Hypervizor Origin:
    tab: Infrastucture
    style: row
    columns: 3
    initiallyCollapsed: true
  Network:
    tab: Infrastucture
    style: row
    columns: 2
  Vpn:
    tab: Infrastucture
    header: false
    style: row
    columns: 1
  Router:
    tab: Infrastucture
    header: false
    style: row
    columns: 2
  Nomad Infrastructure:
    tab: Infrastucture
    style: row
    columns: 3
    disableCollapse: true
  Kubernetes Infrastructure:
    tab: Infrastucture
    style: row
    columns: 3
    disableCollapse: true
  Development:
    tab: Infrastucture
    style: row
    columns: 1
    disableCollapse: true
  Lab Monitoring:
    tab: Infrastucture
    # header: false
    style: row
    columns: 1
    disableCollapse: true
