#ENC[AES256_GCM,data:NcUfR9iCBxg+9AfGEk+gEYQQNjHqEck4rwJhPS1myySUL17Vxqux3Gil0f0B,iv:LghWaatQi89v20plTanU0AZm2rmhxeA8lx4UbFICx68=,tag:Lu51pAJLUBH7DjZGs/Fnlg==,type:comment]
#ENC[AES256_GCM,data:5xesrEsGH3tRAEYky3klfO23HNJdcgjPEadX08LfALN1jrzeFuvlW0OORhDK7gqsQlvCX6ZM2VLse1CbynFq3UB+q1YjNra1AtkwTdHP,iv:g3HbDBZns1HxJQe1atU8NkYaWzp6z0PXakuz3wJ0nPA=,tag:Rs58v+IwFTFlnfGQ4oCHpw==,type:comment]
#ENC[AES256_GCM,data:jvu7GA4J+TOkJ4hQkssk89QnTL7BV6nigyWBunUWJT5QwjXL/D44fCQN9jz03zEt1j1q+z1SX2Ahz0P7JCWvm1v9JxcEQEYnX/YNS3C5EQ==,iv:Ih9Qxh3tLMR33dwbWCrzPa1f0LpxvXByR1A/FfB3bMg=,tag:Ls4zPhGu/U2hMcN1YO5+Yw==,type:comment]
#ENC[AES256_GCM,data:29I+OrJQ0MocumNb9MXBFXI1zzYG/SIAKr7HfCmhd5+CZVw91l7zLMRgmVKSUuo79eccANnyaHXE738+,iv:bE6eL8v/93ozEfNYpBN9ln9GzrgVHkndo2AeLq0X4SA=,tag:5sXVydc6ol20HIW/44Y40w==,type:comment]
HOMEPAGE_VAR_PVE_KVT_TOKEN: ENC[AES256_GCM,data:fsgL30I4o+HxDw7z+QmVZ7uDyaYSrqizhUsNo1eCF3IfcsQo,iv:rk1xC4IEhZtM2+vYGFr+H27t+KjKFSxjdf0CexeKi9w=,tag:rUjGte13lNfSDyUPek1PKg==,type:str]
HOMEPAGE_VAR_PVE_LOCAL_L_01_TOKEN: ENC[AES256_GCM,data:8JXul/zLzNjg7gHRHJXr8OJgTHC4+qTBBbMo5iZplB9eQExX,iv:u3m5NfNlGKNIAY4gHdEdoeSv1uTYcUzDJGs7EQe2U+g=,tag:8RWtA9hT7TbIK996kJ8i2w==,type:str]
HOMEPAGE_VAR_PVE_LOCAL_L_02_TOKEN: ENC[AES256_GCM,data:B/mkxQrOUm7qism3w4WIgZcmJoP/aay2fRZg8vgINvOOw6T1,iv:YFHYg0iBXOlLV1lW6wUcKZdCY4MHUfHLqdf75B1oQds=,tag:jJOF857Jr+tljBQbDo/LYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd1ROYm83QURlanJlSXFw
            TnEwUjg1RXc5QUNab1VEMU9tRFZCV3dqblVRCkFuR2RrT1NxMHRHZUEwSFQxVzhz
            UzZINjNMNkpGeFRRRU5wQ0JDeUE2RjgKLS0tIFZ1azJiSXEySHJVMTAzSng3YjlH
            d1pxYkt0aWFsQW9YWEV0QmVZektMam8KS9u0/3IupzER38LX6H2E6vm3WDXVjC8t
            ynscdawb0kj6oQwWouRrT6Na0tpEHHV/aXdD5oLRZGK7YHU3ZGfkAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1apuqylxr4cxvrrypxjshpn6hf6jf8kqs5uanyfs9d493hmv9wpysgzz8zg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbURLU2k3MENPWCtkOUJr
            VmtLRDIzQXZCcnRMcmRaU0FXK1NYZU5GSEEwCjVDZDdYRXBBekZhZVRaMVpoYXJH
            V2JQb1RLam4zN05rMzNOZVpGR1ltcnMKLS0tIDdoamF4SVoxTUtlUjd3QmxsbTJp
            WElaa2ZNM0xsMzZhYWVWOEdKdGFsSzAKuBjD3h3IldQqJGQ46A0mw0g73Oj7g0iU
            azeWd1H8dcUwuGnwEH4HygSgl8hLoPwtFi81iOT+lMO75rTGqmusbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7w9d59dtx5ksqxfujskjk5xwrt4ftv5czva2zzff2paggggy9nq4q0lxm
    lastmodified: "2026-08-29T16:51:36Z"
    mac: ENC[AES256_GCM,data:w64bM7PbnNb1S/JfrXvbCyDgn1KSC/+Bz3p7YXy9BfSAjF+4MJetVUtYVyaiWr09EwIRv7C3KrnxK2bK0p69ut4SQINP7lliUG/rlw3QsfMBJb1DtMr08oQ56IzRQVKXA+aciExsEbeeXBETqTA8FukJ6pGdyDITzkaQLhW6Wxw=,iv:U7DCjkp+VQM20aJrP1fF35zwNg0YDOJH6GuyNwUR+0g=,tag:0bYmp4CD/kAgKo6jL0492Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
